### ISSUE TITLE
Update libffi to a newer version to support LoongArch

### ISSUE THREAD

**Issue by Panxuefeng-loongson** [jnr/jffi#127]
Hi:

Now the libffi in the jffi repository does not support loongarch yet, upstream libffi already supports loongarch, The libffi of the jffi repository should be synchronized with the upstream to solve the problem @headius 

Thanks

**Comment by headius** [comment]
@Panxuefeng-loongson I think we resolved this already through your other commits, yes?

**Comment by Panxuefeng-loongson** [comment]
> @Panxuefeng-loongson I think we resolved this already through your other commits, yes?

I apologize for not following up on this issue. The problem has been solved.
