### ISSUE TITLE
New jffi version (1.2.8) still not published in maven repository

### ISSUE THREAD

**Issue by lbianc** [jnr/jffi#15]
@headius @enebo 

jffi version 1.2.8 is still not published in maven repository (http://mvnrepository.com/artifact/com.github.jnr/jffi).
I need this version available to be used in JRuby to enable PPC64 support.

Sorry, I dont know the upload process, if necessary any action, please let me know.

Thanks!

**Comment by enebo** [comment]
@lbianc when I tried testing dependent artifacts on top of this newer version of jffi I got some errors and we need to take some time to figure out what is wrong.

**Comment by lbianc** [comment]
@enebo 

Thank you! Btw, is there an issue, page or mail-list that I can track it?

**Comment by gustavotemple** [comment]
@lbianc, yes, here:

https://issues.sonatype.org/browse/OSSRH

**Comment by headius** [comment]
@lbianc There is not, but perhaps we should set one up.

**Comment by headius** [comment]
#16 details a commit I reverted that should allow us to release 1.2.8. With that commit out, jnr-ffi passes all its tests against jffi 1.2.8. There's no reason to believe any of the higher libraries would fail, but we'll test them as well.

Will close this once 1.2.8 is actually released.

**Comment by rtyler** [comment]
@headius is there any testing that we could do over here at @Lookout to get this release out the door?

**Comment by headius** [comment]
I just need @enebo to give the thumbs up and I can push releases out of the related jnr projects.

**Comment by headius** [comment]
We have thumbs up. Starting release process for this and a number of jnr-* upstream projects.

**Comment by headius** [comment]
1.2.8 has been released.
