### ISSUE TITLE
Bad dates in jnr/jffi commits

### ISSUE THREAD

**Issue by cunningt** [jnr/jffi#157]
There seem to be a few commits in jnr/jffi with bad dates in the author/commiter line - can these be fixed?    github is pretty understanding of these but other git related tools and gitlab are not :

```
❯ git clone git@github.com:jnr/jffi.git
Cloning into 'jffi'...
remote: Enumerating objects: 8542, done.
remote: Counting objects: 100% (1128/1128), done.
remote: Compressing objects: 100% (569/569), done.
remote: Total 8542 (delta 506), reused 1059 (delta 478), pack-reused 7414
Receiving objects: 100% (8542/8542), 12.37 MiB | 35.98 MiB/s, done.
Resolving deltas: 100% (3489/3489), done.
❯ cd jffi
❯
❯ git fsck
Checking object directories: 100% (256/256), done.
error in commit d711dc5ed8f54ad0ba303b9f38fe0cd321f861a3: badDate: invalid author/committer line - bad date
error in commit c7eedd2eb19ec6f75128ab6921b1d55befd8c3ca: badDate: invalid author/committer line - bad date
error in commit 086b6b58a838e8257f4aa276cb067c8b54e81408: badDate: invalid author/committer line - bad date
error in commit 300125fb45f0a3228b5e1a3b50c3372f8760fcdb: badDate: invalid author/committer line - bad date
error in commit 90d7eea3d07256a66989a944d6e15286322e1b6b: badDate: invalid author/committer line - bad date
error in commit 9b358a22082d6b32daa6b8147469412d46d1b63d: badDate: invalid author/committer line - bad date
error in commit df31b348967f7fa9cb7f419008974233f2913f3a: badDate: invalid author/committer line - bad date
Checking objects: 100% (8542/8542), done.
```

**Comment by headius** [comment]
Hello! I see you reported similar items in a few other JNR repositories but I will primarily respond here (at the root of the JNR project tree).

The commits in question don't look peculiar locally, but I do indeed get the same results as you when I run `git fsck`. I'm looking into how it can be fixed, but I know about as much as you do right now.

**Comment by headius** [comment]
As a suspected, it doesn't seem like we can do anything about this. The dates are part of the commit, and therefore part of the hash. We would have to replace the commit with a fixed version, which then would mean every downstream commit from there has to also be rewritten to the new hash. Essentially, starting with the earliest bad date commit, we'd have to rewrite the repository.

Many of the commits in these repos are also **signed** by the committer, and rewriting the repository would lose those signatures.

Some of this process is described here: https://stackoverflow.com/a/59231607

I don't really think there's anything we can do. Is there a specific tool that's giving you a hard time with these commits?

**Comment by headius** [comment]
If you are having trouble with a specific tool, let us know and we can try to help. Unfortunately I don't think there's a way to correct this, since it would require rewriting most of the repository and losing audit trail components like signed commits.
