### ISSUE TITLE
GPL License...

### ISSUE THREAD

**Issue by sjerman** [jnr/jffi#19]
Hi Folks,

This file: https://github.com/jnr/jffi/blob/master/jni/libffi/testsuite/lib/libffi.exp
has a GPL license in it. Any change of removing? .. it will prevent some question from IP people (at least in the future :) )

Steve

**Comment by headius** [comment]
We don't run the test suite, so I suppose there's no issue with us removing that.

**Comment by headius** [comment]
@sjerman Actually, I'm confused why it will affect IP. This is a test file for a separate library, not included in binary forms of jffi or the native ffi library. As long as the license is clearly stated, there shouldn't be any issue just having it in the repository.

I can remove the test suite (after confirming it does not ever need to run) but it seems unnecessary.

**Comment by sjerman** [comment]
The issue is that IP scanners pick up the license from the Jar. If the test
suite wasn't in the binary jar, that would work equally well.

Thanks
Steve

**Comment by headius** [comment]
If the test suite is getting included in the jar, that's definitely a bug.

**Comment by sjerman** [comment]
It was a while since i looked at this... I think maybe it was being included in the source jar rather than the binary

**Comment by headius** [comment]
Licenses for the project and contained files are clearly delimited, so I think this is a non-issue. If it becomes an issue for someone in the future, we can look at having these GPL sources fetched only for build or test.
