### ISSUE TITLE
Invoker fails to correctly pass arguments to Foreign is some edge cases.

### ISSUE THREAD

**Issue by bendoerr** [jnr/jffi#22]
I ran into an issue today using JNR-FFI where we are using a mix of Direct and Heap ByteBuffers and had C interface that looked something like `int method(char *c1, char *c2, long c2len, char *c3, char *c4) and I found that depending on where the direct ByteBuffer was in the mix of heap ByteBuffers, either one pointed was passed to the C interface wrong or JNR-FFI refused since it thought the direct object was a heap object. I tracked the issue into the logic in Invoker that sorts out the correct foreign invocation. This only seems to be an issue where N > 3 where the "switch" algorithm is used.

I've added failing unit tests to InvokerTest in pull request #21 that demonstrate the issue.

**Comment by bendoerr** [comment]
Maybe this is a misunderstanding and the bug is in JNR-FFI rather than here. What is objCount (for example at https://github.com/jnr/jffi/blob/master/src/main/java/com/kenai/jffi/Invoker.java#L1424) supposed to represent? The number of both heap and direct objects or just heap? The algorithm works if it is the number of heap objects. However, that is not how JNR-FFI is calling it.

**Comment by headius** [comment]
Oh, I see you had some failing tests in another PR. I'll try to copy those.
