### ISSUE TITLE
Provide an alternative to load libffi from another directory

### ISSUE THREAD

**Issue by abstractj** [jnr/jffi#40]
@headius I'm not sure if I'm missing something. Today on StubLoader, the only way to load Native libraries is reading it from `jni/" + getPlatformName() + "/" + System.mapLibraryName(stubLibraryName)`.

But that represents a problem for us on Keycloak, because there are several restrictions about having native C inside a jar (this is specific to the project). That's easily achieved with maven shade and is not a problem. But now we would like to load libffi, from an external source. For example: `/usr/lib64/libffi.so`.

I tried to override system properties with `-Djava.library.path=/opt/lib64 -Djffi.boot.library.path=/opt/lib64`, without too much success.

I wonder if we could provide an alternative for people with this very specific scenario, to specify the location of libffi. I would be more than happy to provide a PR if that doesn't exist today.

**Comment by headius** [comment]
I agree this would be good to have. We have also run into problems when trying to use jnr-* on platforms that do not have writable filesystems, or that do not allow loading dynamic libraries from the available writable directories. Go for it!

**Comment by headius** [comment]
It seems like we have `jffi.boot.library.path` but it's not working? This is pretty old at this point, but the code I've glanced at does appear like it should try that property before proceeding to other default locations.

**Comment by headius** [comment]
If this is still not working, go ahead and reopen please.
