### ISSUE TITLE
Support Go c-shared library format

### ISSUE THREAD

**Issue by laszlohordos** [jnr/jffi#42]
I wanted to try if it's possible to integrate Go code into Java and I tried the easy sample I found. After I wanted to try the arrays too I found this incompatibility. Go use the special GoSlice type for array so the Java String[] can not be mapped to GoSlice. I assume it would require special TypeMapper and replace the default one with the GoSlice specific. Unfortunately I don't know how to do that so I share the information I gathered to help to improve the project. 

This is a simple Go code which could be compiled `go build -buildmode=c-shared -o libjnr.dylib main.go` and it creates the OSX library name. For other OS the output file name should be changed. 

```
// package name: jnr
package main

import "C"
import (
	"encoding/base64"
	"log"
)

//export Multiply
func Multiply(x int64, y int64) int64 {
	return x * y
}

//export Base64Encode
func Base64Encode(in []byte) ([]string) {
	result := make([]string, 2)
	if len(in) < 1 {
		result[1] = "Error"
	}
	result[0] = base64.StdEncoding.EncodeToString(in)
	return result
}

func main() {
	println("go build -buildmode=c-shared -o libjnr.dylib main.go")

	for i, v := range Base64Encode(make([]byte, 0)) {
		log.Printf("array value at [%d]=%v", i, v)
	}

	for i, v := range Base64Encode([]byte("TEST")) {
		log.Printf("array value at [%d]=%v", i, v)
	}
}
```

The Go generated this .h file, it may help to visualise the GoSlice type.

```
/* Created by "go tool cgo" - DO NOT EDIT. */

/* package command-line-arguments */

/* Start of preamble from import "C" comments.  */




/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef __SIZE_TYPE__ GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

typedef struct { const char *p; GoInt n; } GoString;
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


extern GoInt64 Multiply(GoInt64 p0, GoInt64 p1);

extern GoSlice Base64Encode(GoSlice p0);

#ifdef __cplusplus
}
#endif
```

I just wrote a simple Java Example that just loads the Go shared library from the same location where go creates it under $GOPATH

```
package org.example;


import java.nio.charset.StandardCharsets;

public class App {
    public static interface LibGo {
        long Multiply(long x, long y);

        String[] Base64Encode(byte[] key);
    }

    public static void main(String[] args) throws Exception {
        System.setProperty("jnr.ffi.library.path", "/ FIX-ME $GOPATH/src/example.org/jnr");
        LibGo libc = jnr.ffi.LibraryLoader.create(LibGo.class).load("jnr");

        System.out.println(libc.Multiply(2L, 4L));

        byte[] key = "TEST".getBytes(StandardCharsets.UTF_8);
        String[] res = libc.Base64Encode(key);
        for (int i = 0; i < res.length; i++) {
            System.out.println("array value at [" + i + "]=" + res[i]);
        }
    }
}
```

When I execute the Java I got this exception. 

```
Exception in thread "main" java.lang.RuntimeException: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/example/App$LibGo$jnr$ffi$0.Base64Encode([B)[Ljava/lang/String; @32: areturn
  Reason:
    Type long_2nd (current frame, stack[1]) is not assignable to reference type
  Current Frame:
    bci: @32
    flags: { }
    locals: { 'org/example/App$LibGo$jnr$ffi$0', '[B', integer }
    stack: { long, long_2nd }
  Bytecode:
    0x0000000: b200 0e2a b400 122a b400 162b 033d c600
    0x0000010: 0a09 8402 01a7 0004 091c 9a00 07b6 001c
    0x0000020: b01c 2bb8 0022 4e2b 2d2a b400 26b6 002a
    0x0000030: a7ff f0                                
  Stackmap Table:
    full_frame(@24,{Object[#2],Object[#44],Integer},{Object[#24],Object[#46],Long})
    full_frame(@25,{Object[#2],Object[#44],Integer},{Object[#24],Object[#46],Long,Long})
    same_locals_1_stack_item_frame(@32,Long)
    full_frame(@33,{Object[#2],Object[#44],Integer},{Object[#24],Object[#46],Long,Long})

	at jnr.ffi.provider.jffi.AsmLibraryLoader.generateInterfaceImpl(AsmLibraryLoader.java:247)
	at jnr.ffi.provider.jffi.AsmLibraryLoader.loadLibrary(AsmLibraryLoader.java:89)
	at jnr.ffi.provider.jffi.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:44)
	at jnr.ffi.LibraryLoader.load(LibraryLoader.java:325)
	at jnr.ffi.LibraryLoader.load(LibraryLoader.java:304)
	at org.example.App.main(App.java:18)
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/example/App$LibGo$jnr$ffi$0.Base64Encode([B)[Ljava/lang/String; @32: areturn
  Reason:
    Type long_2nd (current frame, stack[1]) is not assignable to reference type
  Current Frame:
    bci: @32
    flags: { }
    locals: { 'org/example/App$LibGo$jnr$ffi$0', '[B', integer }
    stack: { long, long_2nd }
  Bytecode:
    0x0000000: b200 0e2a b400 122a b400 162b 033d c600
    0x0000010: 0a09 8402 01a7 0004 091c 9a00 07b6 001c
    0x0000020: b01c 2bb8 0022 4e2b 2d2a b400 26b6 002a
    0x0000030: a7ff f0                                
  Stackmap Table:
    full_frame(@24,{Object[#2],Object[#44],Integer},{Object[#24],Object[#46],Long})
    full_frame(@25,{Object[#2],Object[#44],Integer},{Object[#24],Object[#46],Long,Long})
    same_locals_1_stack_item_frame(@32,Long)
    full_frame(@33,{Object[#2],Object[#44],Integer},{Object[#24],Object[#46],Long,Long})

	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at jnr.ffi.provider.jffi.AsmLibraryLoader.generateInterfaceImpl(AsmLibraryLoader.java:236)
	... 5 more
```

**Comment by headius** [comment]
I agree it would be nice to be able to bind in Go libraries. However I'm not quite sure of the best way to implement this either.

**Comment by DemiMarie** [comment]
@headius I think we would need to use libffi OR generate a custom stub in C or assembler.

**Comment by laszlohordos** [comment]
I just want to share the result of my further research. Unfortunately I haven't found any documentation of JNR/JFFI which would explain how to use it properly. The examples are very basic and doesn't cover the richer functionality of the overall library. I was hesitating between pure JNI or JNR and definitely I saw the flexibility of the JNR but I just couldn't figure out the best way to use and not a single clue anywhere over the internet. I just wanted to call a Go implementation where I deal with String or ByteArray and return back with String or ByteArray and in case of error have the capability to report the issue. 

I tried to define my own structs in C and use them and somehow leverage the `@Out` annotation but I wasn't really sure how to use it and when/how to Free the memory. There are examples when memory is allocated in Java and Freed after the call byte what if memory is allocated in Go or C and return.
I also tried the simple ` int doSomething(byte *in, char **out)` scheme and I did a test with a 25Mb array to see the memory consumptions of the process. It was a base64 encoding so Java process started at 25Mb when it loaded the input and after I called  the process it jumped up to 150-170Mb and GC claimed back it after the process so a simple call with JNR and using custom "Strut" made 5-6 copy in Java (I only monitored the Java memory). Mostly these tests and the lack of documentation which let me uncertain about the possible memory leaks and the complete missing best practices about error handling made me to use JNI which result in a simple Java code using JNI native declaration only and in Go I could leverage the full JNI interface and by following the documentation I believe there is no memory leak. Doing the same 25Mb test I got 3 copy only which also convinced me to use JNI. This JNR might have been nice to use and would gave me so more but due to the lack of documentation I was not able to use it for my need. Thank you and wish you happy coding and good luck with this project. I may check it in my next project but now it's a no-go.

**Comment by headius** [comment]
We need more assistance here, if this is actually a good idea. FFI can certainly support these calls, but currently they may require a lot of stitching to work right.

Closing for now, but if someone wants to help us work through some example code, I'm willing to explore the possibilities.
