### ISSUE TITLE
jffi doesn't support for Android at all.

### ISSUE THREAD

**Issue by lygstate** [jnr/jffi#44]
```
java.lang.UnsatisfiedLinkError: dlopen failed: library "libc.so.6" not found
```

On android, there is no libc.so.6 at all.
We should compiling for android independently.

**Comment by headius** [comment]
This does not constitute lack of support. Rather, it means that the "c" library is located somewhere else, or there's something unusual about loading libraries on Android. I have heard that Android prevents dynamically-loaded libraries from seeing other libraries exports by always opening them as RTLD_LOCAL. That could be the cause.

Can you investigate any further?

**Comment by lygstate** [comment]
ah I've already getting jffi works under Android
