### ISSUE TITLE
Support IBM Power architecture on Linux.

### ISSUE THREAD

**Issue by mbruzek** [jnr/jffi#5]
The new IBM Power architecture on Linux does not appear to be supported by jnr/jffi.  The kernel architecture is ppc64le (little endian).

Looking at Java files:
com/kenai/jffi/internal/StubLoader.java
https://github.com/jnr/jffi/blob/master/src/main/java/com/kenai/jffi/internal/StubLoader.java#L159
com/kenai/jffi/Platform.java
https://github.com/jnr/jffi/blob/master/src/main/java/com/kenai/jffi/Platform.java#L196
I do not believe they would match the architecture on ppc64le for the determineCPU() method.

For reference here is the kernel architecture output.

```
$ uname -a
Linux stilson-01 3.13.0-29-generic #53-Ubuntu SMP Wed Jun 4 21:02:53 UTC 2014 ppc64le ppc64le ppc64le GNU/Linux
$ java -version
java version "1.7.0_55"
OpenJDK Runtime Environment (IcedTea 2.4.7) (7u55-2.4.7-1ubuntu1)
OpenJDK 64-Bit Zero VM (build 24.51-b03, interpreted mode)
```

Classes like this use Java system properties to determine architecture.  Here is a listing of the environment properties from OpenJDK running on the same Power system:

```
$ java Jvm
-- listing properties --
java.runtime.name=OpenJDK Runtime Environment
sun.boot.library.path=/usr/lib/jvm/java-7-openjdk-ppc64el/j...
java.vm.version=24.51-b03
java.vm.vendor=Oracle Corporation
java.vendor.url=http://java.oracle.com/
path.separator=:
java.vm.name=OpenJDK 64-Bit Zero VM
file.encoding.pkg=sun.io
user.country=US
sun.java.launcher=SUN_STANDARD
sun.os.patch.level=unknown
java.vm.specification.name=Java Virtual Machine Specification
user.dir=/home/ubuntu/mbruzek/java
java.runtime.version=1.7.0_55-b14
java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment
java.endorsed.dirs=/usr/lib/jvm/java-7-openjdk-ppc64el/j...
**os.arch**=ppc64le
java.io.tmpdir=/tmp
line.separator=

java.vm.specification.vendor=Oracle Corporation
**os.name**=Linux
sun.jnu.encoding=UTF-8
**java.library.path**=/usr/java/packages/lib/ppc64le:/usr/lib/powerpc64le-linux-gnu/jni:/lib/powerpc64le-linux-gnu:/usr/lib/powerpc64le-linux-gnu:/usr/lib/jni:/lib:/usr/lib
java.specification.name=Java Platform API Specification
java.class.version=51.0
os.version=3.13.0-29-generic
user.home=/home/ubuntu
user.timezone=
java.awt.printerjob=sun.print.PSPrinterJob
file.encoding=UTF-8
java.specification.version=1.7
user.name=ubuntu
java.class.path=.
java.vm.specification.version=1.7
**sun.arch.data.model**=64
java.home=/usr/lib/jvm/java-7-openjdk-ppc64el/jre
sun.java.command=Jvm
java.specification.vendor=Oracle Corporation
user.language=en
awt.toolkit=sun.awt.X11.XToolkit
java.vm.info=interpreted mode
java.version=1.7.0_55
java.ext.dirs=/usr/lib/jvm/java-7-openjdk-ppc64el/j...
sun.boot.class.path=/usr/lib/jvm/java-7-openjdk-ppc64el/j...
java.vendor=Oracle Corporation
file.separator=/
java.vendor.url.bug=http://bugreport.sun.com/bugreport/
sun.cpu.endian=little
sun.io.unicode.encoding=UnicodeLittle
sun.cpu.isalist=
```

**Comment by fenglixa** [comment]
I installed Logstash 1.5.0.1, but seems it still cannot work on IBM Power Linux,  ppc64le:

# rpm -qa |grep logstash
logstash-1.5.0-1.noarch

# /opt/logstash/bin/logstash  -f /etc/logstash/conf.d -l /var/log/logstash/logstash.log
io/console not supported; tty will not be manipulated
LoadError: Unsupported platform: unknown-linux
  require at org/jruby/RubyKernel.java:1071
   (root) at /opt/logstash/vendor/jruby/lib/ruby/shared/ffi/ffi.rb:69
  require at org/jruby/RubyKernel.java:1071
   (root) at /opt/logstash/vendor/jruby/lib/ruby/shared/ffi.rb:1
  require at org/jruby/RubyKernel.java:1071
   (root) at /opt/logstash/vendor/jruby/lib/ruby/shared/ffi.rb:1
   (root) at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/util/prctl.rb:1
  require at org/jruby/RubyKernel.java:1071
     LibC at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/util/prctl.rb:4
   (root) at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/util/prctl.rb:3
   (root) at /opt/logstash/lib/bootstrap/environment.rb:48

**Comment by headius** [comment]
What version of JRuby does Logstash 1.5.0.1 ship with? PPC64/LE support
just went out in JRuby 1.7.20 a couple weeks ago. You might be able to swap
it in.

**Comment by fenglixa** [comment]
Thanks headius,
Logstash 1.5.0.1 was bundled with JRuby 1.7.19.
Do you known which version of logstash bundled Jruby1.7.20? Or do you know how to  work-around this issue with Jruby 1.7.19?
Thanks very much!

# ./jruby -v
jruby 1.7.19 (1.9.3p551) 2015-01-29 20786bd on IBM J9 VM pxl6470_27sr2-20141101_01 (SR2) +jit [linux-ppc64le]

**Comment by colinsurprenant** [comment]
@fenglixa we will update to 1.7.20 in 1.5.1/1.6.0, which ever comes first, in the mean time I'd be happy to assist you into building yourself a logstash package with 1.7.20 from the 1.5.0 branch.

**Comment by fenglixa** [comment]
Thanks @colinsurprenant, Please share me the steps for building 1.7.20 from logstash1.5.0, I could try to verify it in my environment first. Thanks.

**Comment by colinsurprenant** [comment]
@fenglixa followed up in elastic/logstash#2747
