### ISSUE TITLE
compile on aarch64,and get error like below:

### ISSUE THREAD

**Issue by ericsoul1987** [jnr/jffi#80]
[exec] /data/jffi-1.0.11/jni/libffi/src/arm/sysv.S: Assembler messages:
     [exec] /data/jffi-1.0.11/jni/libffi/src/arm/sysv.S:53: error： junk at end of line, first unrecognized character is `@'
     [exec] /data/jffi-1.0.11/jni/libffi/src/arm/sysv.S:144: error： junk at end of line, first unrecognized character is `@'
     [exec] /data/jffi-1.0.11/jni/libffi/src/arm/sysv.S:145: error： junk at end of line, first unrecognized character is `@'
     [exec] /data/jffi-1.0.11/jni/libffi/src/arm/sysv.S:146: error： junk at end of line, first unrecognized character is `@'
     [exec] /data/jffi-1.0.11/jni/libffi/src/arm/sysv.S:147: error： junk at end of line, first unrecognized character is `@'
     [exec] /data/jffi-1.0.11/jni/libffi/src/arm/sysv.S:148: error： junk at end of line, first unrecognized character is `@'
     [exec] /data/jffi-1.0.11/jni/libffi/src/arm/sysv.S:149: error： junk at end of line, first unrecognized character is `@'
     [exec] /data/jffi-1.0.11/jni/libffi/src/arm/sysv.S:151: error： junk at end of line, first unrecognized character is `@'
     [exec] /data/jffi-1.0.11/jni/libffi/src/arm/sysv.S:152: error： unknown pseudo-op: `.arm'

waht's the matter with this?

**Comment by headius** [comment]
Hmm, I know I have built jffi on aarch64 before. I notice your build appears to be building jffi 1.0.11, which is many releases old now... possibly even before full aarch64 support was merged in. Can you confirm this on either jffi master or the current release version 1.2.23?

**Comment by headius** [comment]
FWIW, 1.0.11 is nearly nine years old. I'm pretty sure we did not support aarch64 properly back then.

**Comment by ericsoul1987** [comment]
appreciate for your reply.
after using the newest-version's share library ,it works well now.
might you comfirm it is downward compatible?

**Comment by headius** [comment]
@ericsoul1987 We have not made any significant changes to the jffi API in many years, so it's "probably" downward compatible with whatever you are using. You are probably consuming it through something like jnr-ffi, though, which has evolved a bit. I can't really *guarantee* downward compatibility in the rest of jnr-*, but they *should* be ok.

Thank you for confirming this, I'll mark it closed.

**Comment by headius** [comment]
It appears we first merged aarch64 support in 1.2.13.
