### ISSUE TITLE
support ulong_long

### ISSUE THREAD

**Issue by ahorek** [jnr/jffi#87]
```ulong_long``` type is represented as ```long``` which is not enough for corner values

https://github.com/jruby/jruby/blob/b267aa1e495670edcd0c919d92a4228fd3de7944/core/src/main/java/org/jruby/ext/ffi/AbstractMemory.java#L782

https://github.com/ffi/ffi/blob/1091ff7e7efe7bb49231a4a0107dcd2022ed7642/spec/ffi/struct_spec.rb#L367
```
  1) Struct tests ulong_long field r/w (8000000000000000)
     Failure/Error: s[:v] = obj

     RangeError:
       bignum too big to convert into `long'
     # ./spec/ffi/struct_spec.rb:347:in `test_num_field'
     # ./spec/ffi/struct_spec.rb:358:in `block in int_field_test'

  2) Struct tests ulong_long field r/w (ffffffffffffffff)
     Failure/Error: s[:v] = obj

     RangeError:
       bignum too big to convert into `long'
     # ./spec/ffi/struct_spec.rb:347:in `test_num_field'
     # ./spec/ffi/struct_spec.rb:358:in `block in int_field_test'
```

refs https://github.com/jruby/jruby/pull/6375

**Comment by headius** [comment]
I believe these errors are just due to JRuby failing to allow the ulong-ranged values to coerce. We can't represent a ulong directly in Java, but I've modified the related coercion logic in jruby/jruby#6406 to allow those values encoded as a long.
