### ISSUE TITLE
Add support for OSX arm64

### ISSUE THREAD

**Issue by Horcrux7** [jnr/jffi#92]
OSX use now Apple silicon, an ARM 64 (M1) chip. Please add support for it.

**Comment by nirvdrum** [comment]
I'm pretty sure the M1 is not an AMD 64 chip, but that aside, PRs are always welcomed.

**Comment by Horcrux7** [comment]
Sorry my mistake. I always confuse the two.

**Comment by headius** [comment]
Correct... the only thing missing for us to support this is a build of libffi on Apple Silicon. Anything you can do to help push those efforts forward would be welcomed!
